This document was written by Mattia Pasquini.

# Competitions in cantons

In Switzerland there are 26 cantons.

And it shows the statistics about WCA Competitions for each canton.

## Associate the cantons in competitions

It needs to have a csv file to have the association between competition and canton.

I named the file `competitionsAndCantons.csv` (created manually, last update: 18/11/2022) with columns `competitionId` and `canton`.

<span style="color: red"> <b>Warning</b>: I didn't consider the canceled competitions or something else.</span>

Dataset cantons and competitions

In [1]:
import numpy as np
import pandas as pd
cantons = pd.read_csv('competitionsAndCantons.csv')
cantons.index +=1
cantons

               competitionId      canton
1             GenevaOpen2008      Geneve
2              SwissOpen2009        Vaud
3              SwissOpen2014  St. Gallen
4       SwissScienceOpen2014      Zurich
5         SwissNationals2015  St. Gallen
..                       ...         ...
78        SwissNationals2022     Argovia
79       SwisscubingCupV2022   Neuchâtel
80      SwissScienceOpen2022      Zurich
81  SwisscubingCupFinale2022      Zurich
82        Chaeaeswuerfel2022        Bern

[82 rows x 2 columns]

## Import WCA data

Import the competitions and results data from WCA ([link](https://www.worldcubeassociation.org/results/misc/export.html)) and merge with the data of competitionsAndCantons.csv.

In [2]:
# Competitions dataset
competitions = pd.read_csv('WCA_export_Competitions.tsv', sep='\t')

# Results dataset
results = pd.read_csv('WCA_export_Results.tsv', sep='\t')

# merge 'competitionsAndCantons' and wca competition datasets
cc = competitions.merge(cantons, how='inner', left_on='id', right_on='competitionId')
cc.drop(columns='id')

# merge 'competitionsAndCantons' and wca results datasets
rc = results.merge(cantons, how='inner', left_on='competitionId', right_on='competitionId')

## Cantons with the most competitions

In [3]:
cc1 = cc[['name', 'canton']]
nCompCanton = cc1.groupby('canton').count()
nCompCanton = nCompCanton.sort_values(by = 'name', ascending = False)
nCompCanton = nCompCanton.rename(columns = {'name':'competitions'}).reset_index()
nCompCanton.index += 1
nCompCanton

                    canton  competitions
1                   Zurich            14
2                   Ticino            11
3                     Vaud            10
4                     Bern             9
5               St. Gallen             8
6                   Schwyz             5
7                   Geneve             3
8                  Lucerne             3
9                      Zug             2
10                  Wallis             2
11               Thurgovia             2
12               Neuchâtel             2
13            Schaffhausen             2
14                 Argovia             2
15                  Luzern             2
16        Basel-Landschaft             2
17                 Grisons             1
18             Basel-Stadt             1
19  Appenzell Ausserrhoden             1

Zurich hosted more competitions (14). Second is Ticino with 11 comps (I think many people will be surprised for that).

## Cantons partecipated in

In [4]:
# import Persons dataset
persons = pd.read_csv('WCA_export_Persons.tsv', sep='\t')

In [5]:
tb = rc.groupby('personId')['canton'].nunique()
tb = pd.DataFrame(tb).merge(persons, how='inner', left_on='personId', right_on='id')
tb = tb[['name', 'canton']]
tb = tb.sort_values(by = 'canton', ascending = False).reset_index(drop = True)
tb.index += 1
tb.head(12)

                    name  canton
1           Tobias Peter      19
2           Fabian Löhle      18
3           Hannah Minas      18
4         Oleg Gritsenko      18
5           Marco Syfrig      18
6             Theo Mayer      16
7   Ioannis Papadopoulos      16
8      Alistair Robequin      15
9         Matteo Provasi      15
10         Dominik Fürer      15
11       Fabian Settelen      15
12      Yannick Balsiger      15